CREATE TABLE `category_codes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`folderName` varchar(255) NOT NULL,
	`displayName` varchar(255) NOT NULL,
	`code3` varchar(3) NOT NULL,
	`trayCategoriaPrincipal` varchar(255) NOT NULL,
	`traySubcategoria` varchar(255),
	`traySubsubcategoria` varchar(255),
	`driveFolderId` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `category_codes_id` PRIMARY KEY(`id`),
	CONSTRAINT `category_codes_folderName_idx` UNIQUE(`folderName`),
	CONSTRAINT `category_codes_code3_idx` UNIQUE(`code3`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`categoryCodeId` int,
	`sku` varchar(128) NOT NULL,
	`nome` varchar(255) NOT NULL,
	`descricaoHtml` text,
	`slugSeo` varchar(255),
	`precoVenda` decimal(10,2) NOT NULL DEFAULT '199.90',
	`precoCusto` decimal(10,2) NOT NULL DEFAULT '89.90',
	`estoque` int NOT NULL DEFAULT 99,
	`ncm` varchar(20) NOT NULL DEFAULT '4911.99.90',
	`prazoDisponibilidade` int NOT NULL DEFAULT 7,
	`pesoGramas` int NOT NULL DEFAULT 1200,
	`larguraCm` decimal(6,2) NOT NULL DEFAULT '62.00',
	`alturaCm` decimal(6,2) NOT NULL DEFAULT '32.00',
	`comprimentoCm` decimal(6,2) NOT NULL DEFAULT '3.00',
	`marca` varchar(128) NOT NULL DEFAULT 'Qtok Quadros',
	`modelo` varchar(128),
	`ean` varchar(32),
	`tempoGarantia` varchar(64) NOT NULL DEFAULT '30 dias',
	`exibirAtivo` boolean NOT NULL DEFAULT true,
	`exibirNaLoja` boolean NOT NULL DEFAULT true,
	`sourceDriveFileId` varchar(128),
	`sourceDriveFileUrl` text,
	`productDriveFolderId` varchar(128),
	`productDriveFolderUrl` text,
	`imageUrl1` text,
	`imageUrl2` text,
	`imageUrl3` text,
	`imageUrl4` text,
	`imageUrl5` text,
	`aiPotencialVenda` int,
	`aiPalavrasChave` text,
	`aiPublicoAlvo` text,
	`status` enum('suggested','approved','generating','generated','exported','rejected','error') NOT NULL DEFAULT 'suggested',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	`generatedAt` timestamp,
	`exportedAt` timestamp,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_sku_idx` UNIQUE(`sku`)
);
--> statement-breakpoint
ALTER TABLE `users` ADD `googleTokenExpiresAt` timestamp;